use threekeco;

insert into bin (island_id, type) values (1, 1);
insert into bin (island_id, type) values (1, 2);
insert into bin (island_id, type) values (1, 3);
insert into bin (island_id, type) values (1, 4);
insert into bin (island_id, type) values (1, 5);
insert into bin (island_id, type) values (2, 1);
insert into bin (island_id, type) values (2, 2);
insert into bin (island_id, type) values (2, 3);
insert into bin (island_id, type) values (2, 4);
insert into bin (island_id, type) values (2, 5);
insert into bin (island_id, type) values (3, 1);
insert into bin (island_id, type) values (3, 2);
insert into bin (island_id, type) values (3, 3);
insert into bin (island_id, type) values (3, 4);
insert into bin (island_id, type) values (3, 5);
insert into bin (island_id, type) values (4, 1);
insert into bin (island_id, type) values (4, 2);
insert into bin (island_id, type) values (4, 3);
insert into bin (island_id, type) values (4, 4);
insert into bin (island_id, type) values (4, 5);
insert into bin (island_id, type) values (5, 1);
insert into bin (island_id, type) values (5, 2);
insert into bin (island_id, type) values (5, 3);
